version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn package
      - run: yarn lint
      - store_artifacts:
          path: web-ext-artifacts
